<?php

namespace ContainerXEGI5xx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_31SJDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._31SJ_d' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._31SJ_d'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'room' => ['privates', '.errored..service_locator._31SJ_d.App\\Entity\\Room', NULL, 'Cannot autowire service ".service_locator._31SJ_d": it needs an instance of "App\\Entity\\Room" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'room' => 'App\\Entity\\Room',
        ]);
    }
}
