<?php

namespace ContainerXEGI5xx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Zx4ssWcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zx4ssWc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zx4ssWc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'room' => ['privates', '.errored..service_locator.zx4ssWc.App\\Entity\\Room', NULL, 'Cannot autowire service ".service_locator.zx4ssWc": it needs an instance of "App\\Entity\\Room" but this type has been excluded in "config/services.yaml".'],
        ], [
            'room' => 'App\\Entity\\Room',
        ]);
    }
}
