<?php

namespace ContainerXEGI5xx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EnbinDhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EnbinDh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EnbinDh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\RoomController::create' => ['privates', '.service_locator.00tZ8tH', 'get_ServiceLocator_00tZ8tHService', true],
            'App\\Controller\\RoomController::delete' => ['privates', '.service_locator._31SJ_d', 'get_ServiceLocator_31SJDService', true],
            'App\\Controller\\RoomController::index' => ['privates', '.service_locator.0.E_r2b', 'get_ServiceLocator_0_ER2bService', true],
            'App\\Controller\\RoomController::show' => ['privates', '.service_locator.zx4ssWc', 'get_ServiceLocator_Zx4ssWcService', true],
            'App\\Controller\\RoomController::update' => ['privates', '.service_locator._31SJ_d', 'get_ServiceLocator_31SJDService', true],
            'App\\Controller\\RoomController::updateOrder' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\TodoController::create' => ['privates', '.service_locator.f1T71sm', 'get_ServiceLocator_F1T71smService', true],
            'App\\Controller\\TodoController::delete' => ['privates', '.service_locator.fxeykRC', 'get_ServiceLocator_FxeykRCService', true],
            'App\\Controller\\TodoController::generateTodos' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\TodoController::index' => ['privates', '.service_locator.GQxnA83', 'get_ServiceLocator_GQxnA83Service', true],
            'App\\Controller\\TodoController::show' => ['privates', '.service_locator.IWR2fbh', 'get_ServiceLocator_IWR2fbhService', true],
            'App\\Controller\\TodoController::update' => ['privates', '.service_locator.fxeykRC', 'get_ServiceLocator_FxeykRCService', true],
            'App\\Controller\\TodoController::updateOrder' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\RoomController:create' => ['privates', '.service_locator.00tZ8tH', 'get_ServiceLocator_00tZ8tHService', true],
            'App\\Controller\\RoomController:delete' => ['privates', '.service_locator._31SJ_d', 'get_ServiceLocator_31SJDService', true],
            'App\\Controller\\RoomController:index' => ['privates', '.service_locator.0.E_r2b', 'get_ServiceLocator_0_ER2bService', true],
            'App\\Controller\\RoomController:show' => ['privates', '.service_locator.zx4ssWc', 'get_ServiceLocator_Zx4ssWcService', true],
            'App\\Controller\\RoomController:update' => ['privates', '.service_locator._31SJ_d', 'get_ServiceLocator_31SJDService', true],
            'App\\Controller\\RoomController:updateOrder' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\TodoController:create' => ['privates', '.service_locator.f1T71sm', 'get_ServiceLocator_F1T71smService', true],
            'App\\Controller\\TodoController:delete' => ['privates', '.service_locator.fxeykRC', 'get_ServiceLocator_FxeykRCService', true],
            'App\\Controller\\TodoController:generateTodos' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\TodoController:index' => ['privates', '.service_locator.GQxnA83', 'get_ServiceLocator_GQxnA83Service', true],
            'App\\Controller\\TodoController:show' => ['privates', '.service_locator.IWR2fbh', 'get_ServiceLocator_IWR2fbhService', true],
            'App\\Controller\\TodoController:update' => ['privates', '.service_locator.fxeykRC', 'get_ServiceLocator_FxeykRCService', true],
            'App\\Controller\\TodoController:updateOrder' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\RoomController::create' => '?',
            'App\\Controller\\RoomController::delete' => '?',
            'App\\Controller\\RoomController::index' => '?',
            'App\\Controller\\RoomController::show' => '?',
            'App\\Controller\\RoomController::update' => '?',
            'App\\Controller\\RoomController::updateOrder' => '?',
            'App\\Controller\\TodoController::create' => '?',
            'App\\Controller\\TodoController::delete' => '?',
            'App\\Controller\\TodoController::generateTodos' => '?',
            'App\\Controller\\TodoController::index' => '?',
            'App\\Controller\\TodoController::show' => '?',
            'App\\Controller\\TodoController::update' => '?',
            'App\\Controller\\TodoController::updateOrder' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\RoomController:create' => '?',
            'App\\Controller\\RoomController:delete' => '?',
            'App\\Controller\\RoomController:index' => '?',
            'App\\Controller\\RoomController:show' => '?',
            'App\\Controller\\RoomController:update' => '?',
            'App\\Controller\\RoomController:updateOrder' => '?',
            'App\\Controller\\TodoController:create' => '?',
            'App\\Controller\\TodoController:delete' => '?',
            'App\\Controller\\TodoController:generateTodos' => '?',
            'App\\Controller\\TodoController:index' => '?',
            'App\\Controller\\TodoController:show' => '?',
            'App\\Controller\\TodoController:update' => '?',
            'App\\Controller\\TodoController:updateOrder' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
