<?php

namespace ContainerZLixpUh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FxeykRCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fxeykRC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fxeykRC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'todo' => ['privates', '.errored..service_locator.fxeykRC.App\\Entity\\Todo', NULL, 'Cannot autowire service ".service_locator.fxeykRC": it needs an instance of "App\\Entity\\Todo" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'todo' => 'App\\Entity\\Todo',
        ]);
    }
}
