<?php

namespace ContainerZLixpUh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_00tZ8tHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.00tZ8tH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.00tZ8tH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'roomRepository' => ['privates', 'App\\Repository\\RoomRepository', 'getRoomRepositoryService', true],
        ], [
            'em' => '?',
            'roomRepository' => 'App\\Repository\\RoomRepository',
        ]);
    }
}
