<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZLixpUh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZLixpUh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZLixpUh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZLixpUh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZLixpUh\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZLixpUh',
    'container.build_id' => '943f6ec1',
    'container.build_time' => 1726480868,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZLixpUh');
